import React from "react";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
    bademailheadertext:{flexDirection:"row",justifyContent:"center",alignItems:"flex-start"},
    bademailbtn:{backgroundColor:"#4A55BDFF",color:"white",textAlign:"center",fontSize:12,borderRadius:5,padding:5,marginHorizontal:5,overflow:"hidden"},
    bademailheader:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginHorizontal:10,marginVertical:20},
    bademailh1:{justifyContent:"center",alignItems:"center",fontSize:20,paddingVertical:10},
    bademailcontainer2:{backgroundColor:"white",marginHorizontal:10,paddingHorizontal:10,paddingVertical:15,borderRadius:5,overflow:"hidden",marginVertical:15},
    bademailnameh1:{marginHorizontal:10,fontWeight:"bold"},
    bademailp1:{marginTop:10},
    line:{borderBottomWidth:1,borderBottomColor:"black",marginVertical:20},
    bademailinput1:{borderWidth:1,backgroundColor:"#DBCCCD82",borderRadius:5,overflow:"hidden",marginVertical:10,paddingVertical:(Platform.OS=="android"?10:15),paddingHorizontal:(Platform.OS=="android"?5:5)},
    bademailinput2:{borderWidth:1,borderRadius:5,overflow:"hidden",marginTop:10,paddingVertical:(Platform.OS=="android"?10:15),paddingHorizontal:(Platform.OS=="android"?5:5)},
    bademailbtn1:{backgroundColor:"gray",alignSelf:"flex-start",padding:10,borderRadius:5,overflow:"hidden",marginVertical:15},
    errorcolor:{color:"red",marginVertical:5},
    pinputcontainer:{flex:1,flexDirection:"row",alignItems:"center",color:"black",marginLeft:10,height:40,borderBottomWidth:2,borderBottomColor:"black",marginHorizontal:10},
    pinput:{ width:"90%",color:"black"},
    cpbutton:{flex:1,backgroundColor:"black",borderRadius:50,flexDirection:"row",paddingHorizontal:10,paddingVertical:5,justifyContent:"center",marginHorizontal:"20%",marginVertical:10},
    container5: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
      },
      selectedTextStyle: {
        height: 50,
        borderColor: 'gray',
        backgroundColor: 'transparent',
        justifyContent: 'center',
        width: '100%',
        color: 'black',
        fontSize: 14,
        paddingLeft: 5,
        marginTop: -2,
      },
      selectedTextStyle1: {
        height: 50,
        borderColor: 'gray',
        backgroundColor: 'transparent',
        justifyContent: 'center',
        width: '100%',
        color: 'black',
        fontSize: 20,
        paddingLeft: 10,
        marginTop: 15,
      },
      listTextStyle: {
        color: '#000',
        marginVertical: 10,
        flex: 0.9,
        marginLeft: 20,
        marginHorizontal: 10,
        textAlign: 'left',
      },
      searchBarStyle: {
        marginBottom: 10,
        flexDirection: 'row',
        height: 40,
        shadowRadius: 1,
        shadowOpacity: 1.0,
        borderWidth: 1,
        shadowOffset: {
          width: 1,
          height: 1,
        },
        borderColor: '#303030',
        shadowColor: '#303030',
        borderRadius: 5,
        elevation: 1,
        marginHorizontal: 10,
      },
      placeHolderTextStyle: {
        color: 'red',
        padding: 10,
        textAlign: 'left',
        width: '99%',
        flexDirection: 'row',
      },
      dropDownIconStyle: {
        width: 10,
        height: 10,
        left: -40,
        // marginTop: 20,
      },
      dropDownIconStyle1: {
        width: 100,
        height: 10,
        left: -40,
        margin: 15,
      },
      pickerStyle: {
        shadowRadius: 0.5,
        shadowOpacity: 0.5,
        borderBottomWidth: 0,
        shadowOffset: {
          width: 0.5,
          height: 0.5,
        },
        height: 40,
        width:'92%',
        borderBottomColor: '#303030',
        shadowColor: 'transparent',
        borderRadius: 5,
        elevation: 0,
      },
      pickerStyle1: {
        height: 60,
        borderBottomColor: 'dodgerblue',
        borderBottomWidth: 2,
      },
      rbsheetbtn:{
          backgroundColor:"black",
          marginTop: 10, 
          padding: 10, 
          borderRadius: 5,
          marginHorizontal:20,
         

      },
      tpcontainer:{flex:1},
      inputlabel:{marginHorizontal: 10, fontWeight: "bold", marginVertical: 10},
      TPbutton:{flexDirection:"row",justifyContent:"space-between",marginHorizontal:20},
      transactioninput:{marginHorizontal:10,borderBottomWidth:1,borderTopLeftRadius:5,borderTopRightRadius:5}

})