import React, {useEffect, useState} from "react";
import {Text, View, SafeAreaView, TouchableOpacity, FlatList, RefreshControl} from "react-native";
import Colors from "../../../../Style_Sheet/Colors";
import EvilIcons from "react-native-vector-icons/EvilIcons";
import AntDesign from "react-native-vector-icons/AntDesign";
import DoubleText from "../../../../utilis/DoubleText";
import {getcommissionbinary} from "../../../../utilis/Api/Api_controller";
import Toast from "react-native-simple-toast";
import Loader from "../../../../utilis/Loader";
import Dialogs from "../../../../utilis/Dialog";

const BinaryCommission = () => {
    const [visible, setVisible] = useState(false);
    const [isloading,setLoading]=useState(false);
    const [refreshing,setRefreshing]=useState(false);
    const [apiData,setApiData]=useState("");
    const [res,setRes]=useState("");

    useEffect(async ()=>{
        await getData();
    },[]);
    const getData=async ()=>{
        setLoading(true)
        let response = await getcommissionbinary();
        if (response !== "Error") {
            if (response.data.status === true) {
                setApiData(response.data.data);
                setRefreshing(!refreshing)
                setLoading(false);
            }else {
                Toast.show("Something Went Wrong !", Toast.LONG);
                setLoading(false);
            }
        }else {
            Toast.show("Network Error: There is something wrong!", Toast.LONG);
            setLoading(false);
        }
    }
    const onRefresh = async () => {
        await getData();
    }
    const renderItem=({item})=>(
        <TouchableOpacity onPress={()=>{setVisible(true),setRes(item)}} style={{height:110,width:"46.9%", backgroundColor: Colors.secondary, borderColor: Colors.white, borderRadius: 10, borderBottomWidth: 2, padding: 10,margin:"1.5%" }}>
            <Text style={{ fontSize: 14, color: Colors.white }}>{item.pin_code?item.pin_code:"not Available"}</Text>
            <Text style={{ fontSize: 14, color: Colors.white }}>Total ({item.total?parseFloat(item.total).toFixed(1):"not Available"})</Text>
            <Text style={{ fontSize: 14, color: Colors.white }}>Status ({item.status?item.status:"not Available"})</Text>
            <Text style={{ fontSize: 13, color: Colors.lightgray, flex: 1, }}>Activity Date: {item.created_at?item.created_at:"not Available"}</Text>
        </TouchableOpacity>
    )
    return (
        <SafeAreaView style={{flex:1}}>
            {apiData ? null: <Loader animating={isloading}/>}
            <FlatList
                data={apiData}
                renderItem={renderItem}
                numColumns={2}
                style={{ flex: 1 }}
                contentContainerStyle={{ marginVertical: 5 }}
                refreshControl={
                    <RefreshControl
                        refreshing={false}
                        onRefresh={onRefresh} />
                }
            />
            <Dialogs visible={visible} onPress={()=>{setVisible(false)}} title={"Description"}>
                <View style={{backgroundColor:"rgba(61,59,59,0.24)",borderRadius:10}}>
                <Text style={{fontSize:13,paddingHorizontal:10 }}>Pin Code = {res.pin_code?res.pin_code:"not Available"}</Text>
                <Text style={{fontSize:13,paddingHorizontal:10 }}>Pin Package = {res.package_name?res.package_name:"not Available"}</Text>
                <Text style={{fontSize:13,paddingHorizontal:10 }}>Pin Package Price = {res.package_price?res.package_price:"not Available"}</Text>
                <Text style={{fontSize:13,paddingHorizontal:10 }}>Pin Package BV = {res.package_bv?res.package_bv:"not Available"}</Text>
                <Text style={{fontSize:13,paddingHorizontal:10 }}>Generated By = {res.generated_by?res.generated_by:"not Available"}</Text>
                </View>
                <DoubleText text1={"Ref.Code"} text2={res.pin_code?res.pin_code:"not Available"}/>
                <DoubleText text1={"Receiver"} text2={res.user?res.user:"not Available"}/>
                <DoubleText text1={"Generator"} text2={res.fromUser?res.fromUser:"not Available"}/>
                <DoubleText text1={"Side"} text2={res.side?res.side:"not Available"}/>
                <DoubleText text1={"Type"} text2={res.type?res.type:"not Available"}/>
                <DoubleText text1={"Amount"} text2={res.total?res.total:"not Available"}/>
                <DoubleText text1={"Status"} text2={res.status?res.status:"not Available"}/>
                <DoubleText text1={"Closing"} text2={res.closing_date?res.closing_date.slice(0,10):"not Available"}/>
                <DoubleText text1={""} text2={res.closing_date?res.closing_date.slice(11,19):"not Available"}/>
                <DoubleText text1={"Date"} text2={res.created_at?res.created_at.slice(0,10):"not Available"}/>
                <DoubleText text1={""} text2={res.created_at?res.created_at.slice(11,19):"not Available"}/>
            </Dialogs>
        </SafeAreaView>
    )
}
export default BinaryCommission;
